Add the freecell-solver-4.12.0.tar.xz.

shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha256sum freecell-solver-4.12.0.tar.xz
e3e8b0038da98fa346167c734091d1064616dd4990dbd3aeea2156a57b750417  freecell-solver-4.12.0.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha512sum freecell-solver-4.12.0.tar.xz
1e8f46cb317b530dcd772e14e5f981808c7994b323c44aca2b3b884e1af05e00a3c8873285722c0c3199392f8c0a637ac96dbe2e012ef7f123c3a0fc39ee496e  freecell-solver-4.12.0.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$


patsolve version:

commit 92c793f066e356978a0e273445039eeccb9dd9c9
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Tue May 30 19:23:26 2017 +0300

    Cleanups
