Add the freecell-solver-4.8.0.tar.xz.

shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha256sum freecell-solver-4.10.0.tar.xz
eeb5863b801c563e60704409e3aa0a2575de304db9b94be281cb9dd42edd9f59  freecell-solver-4.10.0.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha512sum freecell-solver-4.10.0.tar.xz
097a431e913cd5c5ab26b1c15a1672295b44194710eded22c2b965e87942dafcb85c24c70657498ae3e07e6f2a62d17da36e1c614f90ea72104928f37920c78b  freecell-solver-4.10.0.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$

patsolve version:

commit 92c793f066e356978a0e273445039eeccb9dd9c9
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Tue May 30 19:23:26 2017 +0300

    Cleanups
