Add the freecell-solver-4.14.1.tar.xz.

shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha256sum freecell-solver-4.14.1.tar.xz
b805e1261ebf0e5ae2c1e7877f9553eb06274e84c140badc8f453fb97d235076  freecell-solver-4.14.1.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha512sum freecell-solver-4.14.1.tar.xz
3c66811c37f4700ddcaaac5a66c66426cd7c076c2d55d8b78dfec232924820bf381e308153898ef8dd8832b32f60018be92b6f2bd597102773ed14470fd16b05  freecell-solver-4.14.1.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$

patsolve version:

commit 855ec5bf58cf839b26a60c753a72823437697dcc
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Thu Aug 17 21:03:55 2017 +0300

    Cleanups - typeof
