Add the freecell-solver-4.8.0.tar.xz.

shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha256sum freecell-solver-4.8.0.tar.xz
c3aa7add44f095b6565eb742c149458c3980de74187261a21042df706ea0e408  freecell-solver-4.8.0.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha512sum freecell-solver-4.8.0.tar.xz
13ec34ae50260ff53a0f5dd18234a313b4b808a719ab8b44457dec216b8a8d4748d2344154f72b71959baec1232f92e326fa0df635007a97591f12af891af17d  freecell-solver-4.8.0.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$

patsolve version:

shlomif[fcs]:$pats$ git show
commit 14aefb3e3df42235c09fb3cef35847a5e39668ce
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Tue Jan 17 20:10:53 2017 +0200

    Remove some unneeded includes.
