Add the freecell-solver-4.18.0.tar.xz.

shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha256sum freecell-solver-4.18.0.tar.xz
d6369779837eef203e5a0051031245da772291cf2d6ff9f66555c69bcc8aaab2  freecell-solver-4.18.0.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$ sha512sum freecell-solver-4.18.0.tar.xz
aa6ba724ade171c5b69517136ba97b46e811d330903a4735ef7ff4e44c905c4a91260ac73b76b90e6406ba7dacc1083c422c16f98ba7b647ae891a50732087a4  freecell-solver-4.18.0.tar.xz
shlomif[fcs]:$fcs/Arcs/fc-solve.shlomifish.org-downloads/fc-solve-site-assets/dest/fc-solve$

patsolve version

shlomif[fcs]:$pats$ git show
commit ac8b793df0729bfc5f07e15f919b8628bc2bc2ae (HEAD -> master, origin/master, origin/HEAD)
Author: Shlomi Fish <shlomif@shlomifish.org>
Date:   Thu Mar 22 12:27:44 2018 +0200

    Add attribute to please GCC with some flags.
